# Generated by Django 2.2.28 on 2023-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_asdsf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fjfjf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kff', models.BigIntegerField()),
                ('jfr', models.BigIntegerField()),
            ],
        ),
    ]
